/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#00174b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffddb2",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#b4c5ff",
        "primary": "#735c00",
        "on-surface": "#1f1b13",
        "outline": "#7f7663",
        "surface-dim": "#e1d9cc",
        "background": "#F7F4EF",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#e9c349",
        "error-container": "#ffdad6",
        "surface": "#F7F4EF",
        "surface-tint": "#735c00",
        "outline-variant": "#d0c5af",
        "on-surface-variant": "#4d4635",
        "tertiary-container": "#97b0ff",
        "primary-fixed-dim": "#e9c349",
        "tertiary": "#415ba4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785725",
        "on-primary-fixed": "#241a00",
        "secondary": "#795826",
        "primary-container": "#d4af37",
        "surface-container-low": "#fbf3e5",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#574500",
        "on-tertiary-fixed-variant": "#27438a",
        "surface-container": "#f5eddf",
        "tertiary-fixed": "#dbe1ff",
        "surface-container-highest": "#eae1d4",
        "on-primary-container": "#554300",
        "surface-variant": "#eae1d4",
        "secondary-container": "#fdd092",
        "on-primary": "#ffffff",
        "surface-container-high": "#efe7da",
        "inverse-on-surface": "#f8f0e2",
        "on-secondary-fixed": "#291800",
        "on-background": "#1f1b13",
        "primary-fixed": "#ffe088",
        "surface-bright": "#F7F4EF",
        "on-tertiary-container": "#254188",
        "on-secondary-fixed-variant": "#5f4110",
        "secondary-fixed-dim": "#ebbf83",
        "on-error-container": "#93000a",
        "inverse-surface": "#343027"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-md": "24px",
        "unit": "4px",
        "stack-lg": "48px",
        "stack-sm": "8px"
      },
      fontFamily: {
        display: ["Alex Brush", "cursive"],
        playfair: ["Playfair Display", "serif"],
        body: ["Montserrat", "sans-serif"],
      }
    },
  },
  plugins: [],
}
